namespace SapGui.Wrapper;

/// <summary>
/// Represents a single SAP GUI session (one window / logon).
/// This is the primary object used for day-to-day automation.
/// 
/// Equivalent to the VBA <c>GuiSession</c> object.
/// </summary>
public class GuiSession : GuiComponent
{
    internal GuiSession(object raw) : base(raw) { }

    // ── Properties ────────────────────────────────────────────────────────────

    /// <summary>Session info, e.g. system ID, client, user.</summary>
    public GuiSessionInfo Info => new(GetRawInfo());

    /// <summary>Whether the session is currently busy processing a request.</summary>
    public bool IsBusy => GetBool("Busy");

    /// <summary>
    /// Returns the currently active (focused) window in this session.
    /// Equivalent to the VBA <c>session.ActiveWindow</c> property.
    /// Useful to detect which <c>wnd[x]</c> has focus without guessing the index.
    /// </summary>
    public GuiMainWindow ActiveWindow
    {
        get
        {
            var raw = Invoke("ActiveWindow")
                      ?? throw new InvalidOperationException("Could not retrieve ActiveWindow.");
            return new GuiMainWindow(raw);
        }
    }

    // ── Session management ────────────────────────────────────────────────────

    /// <summary>
    /// Opens a new parallel SAP session on the same connection.
    /// The new session appears as the next child in the parent connection's
    /// Children collection (<c>Children[n]</c>).
    /// Equivalent to the VBA <c>session.CreateSession()</c>.
    /// <para>
    /// The method returns immediately; poll
    /// <see cref="GuiConnection.GetSessions"/> afterwards to obtain the new
    /// <see cref="GuiSession"/> object.
    /// </para>
    /// </summary>
    public void CreateSession() => Invoke("CreateSession");

    // ── Core FindById (mirrors the VBA session.findById) ─────────────────────

    /// <summary>
    /// Alias for <see cref="FindByIdDynamic"/> using the exact camelCase name
    /// generated by the SAP Script Recorder.
    /// Lets you paste recorder output into C# with only one mechanical change:
    /// adding <c>()</c> after argument-less method calls (<c>.press</c> → <c>.press()</c>).
    /// <para>Example – recorder VBScript:</para>
    /// <code>
    /// session.findById("wnd[0]").maximize
    /// session.findById("wnd[0]/usr/ctxtCATSFIELDS-PERNR").text = "47161"
    /// session.findById("wnd[0]/tbar[1]/btn[5]").press
    /// session.findById("wnd[0]").sendVKey 0
    /// </code>
    /// <para>C# equivalent (only parentheses added):</para>
    /// <code>
    /// session.findById("wnd[0]").maximize();
    /// session.findById("wnd[0]/usr/ctxtCATSFIELDS-PERNR").text = "47161";
    /// session.findById("wnd[0]/tbar[1]/btn[5]").press();
    /// session.findById("wnd[0]").sendVKey(0);
    /// </code>
    /// </summary>
    public dynamic findById(string id) => FindByIdDynamic(id);

    /// <summary>
    /// Finds any GUI component by its ID path, e.g.
    /// <c>"wnd[0]/usr/txtRSYST-BNAME"</c>.
    /// Returns the raw COM object; prefer the typed overloads below.
    /// </summary>
    public GuiComponent FindById(string id)
    {
        object raw;
        try
        {
            raw = Invoke("FindById", id)
                  ?? throw new SapComponentNotFoundException(id);
        }
        catch (Exception ex) when (ex is not SapComponentNotFoundException)
        {
            throw new SapComponentNotFoundException(id, ex);
        }

        return WrapComponent(raw);
    }

    /// <summary>Finds a component and casts it to <typeparamref name="T"/>.</summary>
    public T FindById<T>(string id) where T : GuiComponent
    {
        var component = FindById(id);
        if (component is T typed) return typed;
        throw new InvalidCastException(
            $"Component '{id}' is of type '{component.TypeName}', not '{typeof(T).Name}'.");
    }

    /// <summary>
    /// Finds a component by ID and returns it as <see langword="dynamic"/>.
    /// This allows 1:1 copy-paste of SAP Script Recorder output without any
    /// type casting, because every property and method access is resolved at
    /// runtime via late binding – exactly like VBScript does it.
    /// <para>
    /// Recorder generates:<br/>
    /// <c>session.findById("wnd[0]/usr/txtRSYST-BNAME").Text = "user"</c><br/>
    /// <c>session.findById("wnd[0]/tbar[0]/btn[0]").press()</c>
    /// </para>
    /// <para>
    /// C# equivalent using this method:<br/>
    /// <c>session.FindByIdDynamic("wnd[0]/usr/txtRSYST-BNAME").Text = "user";</c><br/>
    /// <c>session.FindByIdDynamic("wnd[0]/tbar[0]/btn[0]").Press();</c>
    /// </para>
    /// <para>
    /// Note: for typed access with IntelliSense use <see cref="FindById(string)"/> instead.
    /// </para>
    /// </summary>
    public dynamic FindByIdDynamic(string id)
    {
        object raw;
        try
        {
            raw = Invoke("FindById", id)
                  ?? throw new SapComponentNotFoundException(id);
        }
        catch (Exception ex) when (ex is not SapComponentNotFoundException)
        {
            throw new SapComponentNotFoundException(id, ex);
        }
        return raw;
    }

    // ── Typed convenience finders ─────────────────────────────────────────────

    /// <summary>Returns a text field by ID.</summary>
    public GuiTextField  TextField(string id)  => FindById<GuiTextField>(id);

    /// <summary>Returns a button by ID.</summary>
    public GuiButton     Button(string id)     => FindById<GuiButton>(id);

    /// <summary>Returns a combo box by ID.</summary>
    public GuiComboBox   ComboBox(string id)   => FindById<GuiComboBox>(id);

    /// <summary>Returns a check box by ID.</summary>
    public GuiCheckBox      CheckBox(string id)     => FindById<GuiCheckBox>(id);

    /// <summary>Returns a radio button by ID.</summary>
    public GuiRadioButton   RadioButton(string id)  => FindById<GuiRadioButton>(id);

    /// <summary>Returns a label by ID.</summary>
    public GuiLabel      Label(string id)      => FindById<GuiLabel>(id);

    /// <summary>Returns the status bar.</summary>
    public GuiStatusbar  Statusbar()           => FindById<GuiStatusbar>("wnd[0]/sbar");

    /// <summary>Returns the main window.</summary>
    public GuiMainWindow MainWindow()          => FindById<GuiMainWindow>("wnd[0]");

    /// <summary>Returns a <see cref="GuiTable"/> by ID.</summary>
    public GuiTable      Table(string id)      => FindById<GuiTable>(id);

    /// <summary>Returns a <see cref="GuiGridView"/> by ID.</summary>
    public GuiGridView       GridView(string id)    => FindById<GuiGridView>(id);

    /// <summary>Returns a <see cref="GuiTabStrip"/> by ID.</summary>
    public GuiTabStrip       TabStrip(string id)    => FindById<GuiTabStrip>(id);

    /// <summary>Returns a <see cref="GuiTab"/> by ID.</summary>
    public GuiTab            Tab(string id)         => FindById<GuiTab>(id);

    /// <summary>Returns the application toolbar (tbar[1]) or a toolbar by ID.</summary>
    public GuiToolbar        Toolbar(string id = "wnd[0]/tbar[1]") => FindById<GuiToolbar>(id);

    /// <summary>Returns the menu bar.</summary>
    public GuiMenubar        Menubar()              => FindById<GuiMenubar>("wnd[0]/mbar");

    /// <summary>Returns a menu item by ID, e.g. <c>"wnd[0]/mbar/menu[3]/menu[0]"</c>.</summary>
    public GuiMenu           Menu(string id)        => FindById<GuiMenu>(id);

    /// <summary>
    /// Returns the active modal popup window (<see cref="GuiMessageWindow"/>), or
    /// <see langword="null"/> if no popup is currently visible.
    /// Equivalent to checking <c>wnd[1]</c> / <c>wnd[2]</c> etc.
    /// <para>
    /// Handles both SAP <c>GuiMessageWindow</c> (pure message dialogs) and
    /// <c>GuiModalWindow</c> (general modal dialogs, e.g. dialog boxes with form fields).
    /// Both are returned as a <see cref="GuiMessageWindow"/> so that callers can use
    /// <see cref="GuiMessageWindow.ClickOk"/>, <see cref="GuiMessageWindow.ClickCancel"/>,
    /// and <see cref="GuiMessageWindow.GetButtons"/> uniformly.
    /// </para>
    /// </summary>
    public GuiMessageWindow? GetActivePopup(int wndIndex = 1)
    {
        try
        {
            var component = FindById($"wnd[{wndIndex}]");
            return component switch
            {
                GuiMessageWindow mw => mw,
                // GuiModalWindow is wrapped as GuiMainWindow by WrapComponent;
                // re-wrap the raw object as GuiMessageWindow so popup helpers work.
                GuiMainWindow    mw => new GuiMessageWindow(mw.RawObject),
                _                  => null,
            };
        }
        catch { return null; }
    }

    /// <summary>Returns a <see cref="GuiTree"/> by ID.</summary>
    public GuiTree           Tree(string id)        => FindById<GuiTree>(id);

    /// <summary>
    /// Enters a transaction code, same as typing it in the command field and pressing Enter.
    /// </summary>
    public void StartTransaction(string tCode)
    {
        FindById<GuiTextField>("wnd[0]/tbar[0]/okcd").Text = tCode;
        MainWindow().SendVKey(0); // VKey 0 = Enter
    }

    /// <summary>
    /// Exits the current transaction and returns to the SAP Easy Access menu.
    /// Equivalent to typing <c>/n</c> in the command field and pressing Enter.
    /// <para>
    /// Use <c>/nXX</c> via <see cref="StartTransaction"/> to jump directly to another
    /// transaction without returning to the menu first.
    /// </para>
    /// </summary>
    public void ExitTransaction()
    {
        FindById<GuiTextField>("wnd[0]/tbar[0]/okcd").Text = "/n";
        MainWindow().SendVKey(0);
    }

    /// <summary>
    /// Sends a virtual key to the main window.
    /// <para>Common VKey codes:</para>
    /// <list type="table">
    ///   <listheader><term>VKey</term><description>Action</description></listheader>
    ///   <item><term>0</term> <description>Enter</description></item>
    ///   <item><term>3</term> <description>F3 — Back (one screen back within the transaction)</description></item>
    ///   <item><term>4</term> <description>F4 — Input Help / Possible Values</description></item>
    ///   <item><term>8</term> <description>F8 — Execute (runs the current report or selection screen)</description></item>
    ///   <item><term>11</term><description>Ctrl+S — Save</description></item>
    ///   <item><term>12</term><description>F12 — Cancel (discards changes and closes the current screen)</description></item>
    ///   <item><term>15</term><description>Shift+F3 — Exit (steps back to the previous menu level)</description></item>
    /// </list>
    /// </summary>
    public void SendVKey(int vKey) => MainWindow().SendVKey(vKey);

    /// <summary>Presses Enter on the main window (VKey 0).</summary>
    public void PressEnter() => SendVKey(0);

    /// <summary>Presses F3 / Back on the main window (VKey 3).</summary>
    public void PressBack() => SendVKey(3);

    /// <summary>
    /// Presses F8 / Execute on the main window (VKey 8).
    /// Equivalent to clicking the Execute button (<c>tbar[1]/btn[8]</c>) on a
    /// selection screen or transaction initial screen.
    /// </summary>
    public void PressExecute() => SendVKey(8);

    // ── Wait helper ───────────────────────────────────────────────────────────

    /// <summary>
    /// Waits until the session is no longer busy, polling every
    /// <paramref name="pollMs"/> milliseconds up to <paramref name="timeoutMs"/>.
    /// </summary>
    public void WaitReady(int timeoutMs = 30_000, int pollMs = 200)
    {
        var deadline = DateTime.UtcNow.AddMilliseconds(timeoutMs);
        while (IsBusy && DateTime.UtcNow < deadline)
            System.Threading.Thread.Sleep(pollMs);

        if (IsBusy)
            throw new TimeoutException($"SAP session was still busy after {timeoutMs} ms.");
    }

    // ── Events ────────────────────────────────────────────────────────────────

    /// <summary>
    /// Fires after every SAP server round-trip completes (IsBusy transitions
    /// from <see langword="true"/> to <see langword="false"/>).
    /// Provides a snapshot of the status bar text and message type.
    /// <para>
    /// Call <see cref="StartMonitoring"/> to begin receiving events.
    /// </para>
    /// </summary>
    public event EventHandler<SessionChangeEventArgs>? Change;

    /// <summary>
    /// Fires when the session can no longer be accessed (i.e. the user closed
    /// the window or the connection was terminated).
    /// <para>
    /// Call <see cref="StartMonitoring"/> to begin receiving events.
    /// </para>
    /// </summary>
    public event EventHandler? Destroy;

    /// <summary>
    /// Fires when an ABAP abend is detected on the status bar
    /// (message type <c>A</c> after a round-trip).
    /// <para>
    /// Call <see cref="StartMonitoring"/> to begin receiving events.
    /// </para>
    /// </summary>
    public event EventHandler<AbapRuntimeErrorEventArgs>? AbapRuntimeError;

    private SessionEventMonitor? _monitor;

    /// <summary>
    /// Starts a background polling monitor that raises <see cref="Change"/>,
    /// <see cref="Destroy"/>, and <see cref="AbapRuntimeError"/> .NET events.
    /// <para>
    /// Safe to call multiple times (a second call is a no-op if already running).
    /// Call <see cref="StopMonitoring"/> or dispose of the session to stop the
    /// background thread.
    /// </para>
    /// </summary>
    /// <param name="pollMs">
    /// Polling interval in milliseconds. Default is 500 ms.
    /// Lower values produce more responsive events at the cost of CPU.
    /// </param>
    public void StartMonitoring(int pollMs = 500)
    {
        if (_monitor is not null) return;
        _monitor = new SessionEventMonitor(this, pollMs);
    }

    /// <summary>Stops the background polling monitor started by <see cref="StartMonitoring"/>.</summary>
    public void StopMonitoring()
    {
        _monitor?.Dispose();
        _monitor = null;
    }

    // ── Internal event raisers (called by SessionEventMonitor) ────────────────

    internal void RaiseChange(SessionChangeEventArgs args) =>
        Change?.Invoke(this, args);

    internal void RaiseDestroy() =>
        Destroy?.Invoke(this, EventArgs.Empty);

    internal void RaiseAbapRuntimeError(AbapRuntimeErrorEventArgs args) =>
        AbapRuntimeError?.Invoke(this, args);

    // ── Internal helpers ──────────────────────────────────────────────────────

    private object GetRawInfo()
    {
        return Invoke("Info")
               ?? throw new InvalidOperationException("Could not retrieve session Info object.");
    }

    /// <summary>
    /// Wraps a raw COM component object in the appropriate typed wrapper.
    /// </summary>
    internal static GuiComponent WrapComponent(object raw)
    {
        var typeName = string.Empty;
        try
        {
            typeName = (string?)raw.GetType()
                                   .InvokeMember("Type",
                                                 BindingFlags.GetProperty,
                                                 null, raw, null) ?? string.Empty;
        }
        catch { /* unknown type */ }

        return SapComponentTypeHelper.FromString(typeName) switch
        {
            SapComponentType.GuiMainWindow    or
            SapComponentType.GuiFrameWindow   or
            SapComponentType.GuiModalWindow   => new GuiMainWindow(raw),

            SapComponentType.GuiTextField     or
            SapComponentType.GuiCTextField    or
            SapComponentType.GuiPasswordField or
            SapComponentType.GuiOkCodeField   => new GuiTextField(raw),

            SapComponentType.GuiButton        => new GuiButton(raw),
            SapComponentType.GuiCheckBox      => new GuiCheckBox(raw),
            SapComponentType.GuiRadioButton   => new GuiRadioButton(raw),
            SapComponentType.GuiComboBox      => new GuiComboBox(raw),
            SapComponentType.GuiLabel         => new GuiLabel(raw),
            SapComponentType.GuiStatusbar     => new GuiStatusbar(raw),
            SapComponentType.GuiTable         => new GuiTable(raw),
            SapComponentType.GuiGridView      => new GuiGridView(raw),
            SapComponentType.GuiTree          => new GuiTree(raw),
            SapComponentType.GuiTabStrip      => new GuiTabStrip(raw),
            SapComponentType.GuiTab           => new GuiTab(raw),
            SapComponentType.GuiToolbar       => new GuiToolbar(raw),
            SapComponentType.GuiMenubar       => new GuiMenubar(raw),
            SapComponentType.GuiMenu          or
            SapComponentType.GuiSubMenu       => new GuiMenu(raw),
            SapComponentType.GuiContextMenu   => new GuiContextMenu(raw),
            SapComponentType.GuiMessageWindow => new GuiMessageWindow(raw),
            _                                 => new GuiComponent(raw),
        };
    }
}

// ── Session info record ───────────────────────────────────────────────────────

/// <summary>Read-only snapshot of <c>GuiSessionInfo</c> properties.</summary>
public class GuiSessionInfo
{
    private readonly object _raw;

    internal GuiSessionInfo(object raw) { _raw = raw; }

    private string Get(string prop)
    {
        try
        {
            return (string?)(_raw.GetType()
                                  .InvokeMember(prop,
                                                BindingFlags.GetProperty,
                                                null, _raw, null)) ?? string.Empty;
        }
        catch { return string.Empty; }
    }

    /// <summary>SAP system ID (SID), e.g. <c>GP1</c>.</summary>
    public string SystemName     => Get("SystemName");

    /// <summary>Login client number, e.g. <c>450</c>.</summary>
    public string Client         => Get("Client");

    /// <summary>Logged-on user name.</summary>
    public string User           => Get("User");

    /// <summary>Login language, e.g. <c>EN</c>.</summary>
    public string Language       => Get("Language");

    /// <summary>Active transaction code.</summary>
    public string Transaction    => Get("Transaction");

    /// <summary>Active ABAP program name.</summary>
    public string Program        => Get("Program");

    /// <summary>Current screen / dynpro number.</summary>
    public string ScreenNumber   => Get("ScreenNumber");

    /// <summary>Application server hostname.</summary>
    public string ApplicationServer => Get("ApplicationServer");

    /// <inheritdoc/>
    public override string ToString() =>
        $"System={SystemName} Client={Client} User={User} TCode={Transaction}";
}
