using SapGui.Wrapper.Com;

namespace SapGui.Wrapper;

/// <summary>
/// Represents a single SAP GUI session (one window / logon).
/// This is the primary object used for day-to-day automation.
/// 
/// Equivalent to the VBA <c>GuiSession</c> object.
/// </summary>
public class GuiSession : GuiComponent, IDisposable
{
    private bool _disposed;

    /// <summary>
    /// Logging bridge injected by <see cref="SapGuiClient"/> after the session is obtained.
    /// Defaults to the silent no-op logger. Assign via <see cref="SapGuiClient.Attach(SapLogAction?, SapLogLevel, ILogger?)"/>.
    /// </summary>
    internal SapLogger Logger { get; set; } = SapLogger.Null;

    internal GuiSession(object raw) : base(raw) { }

    // ── Properties ────────────────────────────────────────────────────────────

    /// <summary>Session info, e.g. system ID, client, user.</summary>
    public GuiSessionInfo Info => new(GetRawInfo());

    /// <summary>Whether the session is currently busy processing a request.</summary>
    public bool IsBusy => GetBool("Busy");

    /// <summary>
    /// Returns the currently active (focused) window in this session.
    /// Equivalent to the VBA <c>session.ActiveWindow</c> property.
    /// Useful to detect which <c>wnd[x]</c> has focus without guessing the index.
    /// </summary>
    public GuiMainWindow ActiveWindow
    {
        get
        {
            var raw = Invoke("ActiveWindow")
                      ?? throw new InvalidOperationException("Could not retrieve ActiveWindow.");
            return new GuiMainWindow(raw);
        }
    }

    // ── Session management ────────────────────────────────────────────────────

    /// <summary>
    /// Opens a new parallel SAP session on the same connection.
    /// The new session appears as the next child in the parent connection's
    /// Children collection (<c>Children[n]</c>).
    /// Equivalent to the VBA <c>session.CreateSession()</c>.
    /// <para>
    /// The method returns immediately; poll
    /// <see cref="GuiConnection.GetSessions"/> afterwards to obtain the new
    /// <see cref="GuiSession"/> object.
    /// </para>
    /// </summary>
    public void CreateSession() => Invoke("CreateSession");

    // ── Core FindById (mirrors the VBA session.findById) ─────────────────────

    /// <summary>
    /// Alias for <see cref="FindByIdDynamic"/> using the exact camelCase name
    /// generated by the SAP Script Recorder.
    /// Lets you paste recorder output into C# with only one mechanical change:
    /// adding <c>()</c> after argument-less method calls (<c>.press</c> → <c>.press()</c>).
    /// <para>Example – recorder VBScript:</para>
    /// <code>
    /// session.findById("wnd[0]").maximize
    /// session.findById("wnd[0]/usr/ctxtCATSFIELDS-PERNR").text = "47161"
    /// session.findById("wnd[0]/tbar[1]/btn[5]").press
    /// session.findById("wnd[0]").sendVKey 0
    /// </code>
    /// <para>C# equivalent (only parentheses added):</para>
    /// <code>
    /// session.findById("wnd[0]").maximize();
    /// session.findById("wnd[0]/usr/ctxtCATSFIELDS-PERNR").text = "47161";
    /// session.findById("wnd[0]/tbar[1]/btn[5]").press();
    /// session.findById("wnd[0]").sendVKey(0);
    /// </code>
    /// </summary>
    public dynamic findById(string id) => FindByIdDynamic(id);

    /// <summary>
    /// Finds any GUI component by its ID path, e.g.
    /// <c>"wnd[0]/usr/txtRSYST-BNAME"</c>.
    /// Returns the raw COM object; prefer the typed overloads below.
    /// </summary>
    public GuiComponent FindById(string id)
    {
        Logger.Debug($"FindById: {id}");
        object raw;
        try
        {
            raw = Invoke("FindById", id)
                  ?? throw new SapComponentNotFoundException(id);
        }
        catch (SapComponentNotFoundException)
        {
            throw;
        }
        catch (Exception ex)
        {
            throw new SapComponentNotFoundException(id, ex);
        }

        return WrapComponent(raw);
    }

    /// <summary>Finds a component and casts it to <typeparamref name="T"/>.</summary>
    public T FindById<T>(string id) where T : GuiComponent
    {
        var component = FindById(id);
        if (component is T typed) return typed;
        throw new InvalidCastException(
            $"Component '{id}' is of type '{component.TypeName}', not '{typeof(T).Name}'.");
    }

    /// <summary>
    /// Finds a component by ID and returns it as <see langword="dynamic"/>.
    /// This allows 1:1 copy-paste of SAP Script Recorder output without any
    /// type casting, because every property and method access is resolved at
    /// runtime via late binding – exactly like VBScript does it.
    /// <para>
    /// Recorder generates:<br/>
    /// <c>session.findById("wnd[0]/usr/txtRSYST-BNAME").Text = "user"</c><br/>
    /// <c>session.findById("wnd[0]/tbar[0]/btn[0]").press()</c>
    /// </para>
    /// <para>
    /// C# equivalent using this method:<br/>
    /// <c>session.FindByIdDynamic("wnd[0]/usr/txtRSYST-BNAME").Text = "user";</c><br/>
    /// <c>session.FindByIdDynamic("wnd[0]/tbar[0]/btn[0]").Press();</c>
    /// </para>
    /// <para>
    /// Note: for typed access with IntelliSense use <see cref="FindById(string)"/> instead.
    /// </para>
    /// </summary>
    public dynamic FindByIdDynamic(string id)
    {
        Logger.Debug($"FindById (dynamic): {id}");
        object raw;
        try
        {
            raw = Invoke("FindById", id)
                  ?? throw new SapComponentNotFoundException(id);
        }
        catch (SapComponentNotFoundException)
        {
            throw;
        }
        catch (Exception ex)
        {
            throw new SapComponentNotFoundException(id, ex);
        }
        return raw;
    }

    // ── Typed convenience finders ─────────────────────────────────────────────

    /// <summary>Returns a text field by ID.</summary>
    public GuiTextField TextField(string id) => FindById<GuiTextField>(id);

    /// <summary>Returns a button by ID.</summary>
    public GuiButton Button(string id) => FindById<GuiButton>(id);

    /// <summary>Returns a combo box by ID.</summary>
    public GuiComboBox ComboBox(string id) => FindById<GuiComboBox>(id);

    /// <summary>Returns a check box by ID.</summary>
    public GuiCheckBox CheckBox(string id) => FindById<GuiCheckBox>(id);

    /// <summary>Returns a radio button by ID.</summary>
    public GuiRadioButton RadioButton(string id) => FindById<GuiRadioButton>(id);

    /// <summary>Returns a label by ID.</summary>
    public GuiLabel Label(string id) => FindById<GuiLabel>(id);

    /// <summary>Returns the status bar.</summary>
    public GuiStatusbar Statusbar() => FindById<GuiStatusbar>("wnd[0]/sbar");

    /// <summary>Returns the main window.</summary>
    public GuiMainWindow MainWindow() => FindById<GuiMainWindow>("wnd[0]");

    /// <summary>Returns a <see cref="GuiTable"/> by ID.</summary>
    public GuiTable Table(string id)
    {
        var tbl = FindById<GuiTable>(id);
        tbl.SetRebind(() => FindById(id).RawObject);
        return tbl;
    }

    /// <summary>Returns a <see cref="GuiGridView"/> by ID.</summary>
    public GuiGridView GridView(string id) => FindById<GuiGridView>(id);

    /// <summary>Returns a <see cref="GuiTabStrip"/> by ID.</summary>
    public GuiTabStrip TabStrip(string id) => FindById<GuiTabStrip>(id);

    /// <summary>Returns a <see cref="GuiTab"/> by ID.</summary>
    public GuiTab Tab(string id) => FindById<GuiTab>(id);

    /// <summary>Returns the application toolbar (tbar[1]) or a toolbar by ID.</summary>
    public GuiToolbar Toolbar(string id = "wnd[0]/tbar[1]") => FindById<GuiToolbar>(id);

    /// <summary>Returns the menu bar.</summary>
    public GuiMenubar Menubar() => FindById<GuiMenubar>("wnd[0]/mbar");

    /// <summary>Returns a menu item by ID, e.g. <c>"wnd[0]/mbar/menu[3]/menu[0]"</c>.</summary>
    public GuiMenu Menu(string id) => FindById<GuiMenu>(id);

    /// <summary>
    /// Returns the active modal popup window (<see cref="GuiMessageWindow"/>), or
    /// <see langword="null"/> if no popup is currently visible.
    /// Equivalent to checking <c>wnd[1]</c> / <c>wnd[2]</c> etc.
    /// <para>
    /// Handles both SAP <c>GuiMessageWindow</c> (pure message dialogs) and
    /// <c>GuiModalWindow</c> (general modal dialogs, e.g. dialog boxes with form fields).
    /// Both are returned as a <see cref="GuiMessageWindow"/> so that callers can use
    /// <see cref="GuiMessageWindow.ClickOk"/>, <see cref="GuiMessageWindow.ClickCancel"/>,
    /// and <see cref="GuiMessageWindow.GetButtons"/> uniformly.
    /// </para>
    /// </summary>
    public GuiMessageWindow? GetActivePopup(int wndIndex = 1)
    {
        try
        {
            var component = FindById($"wnd[{wndIndex}]");
            return component switch
            {
                GuiMessageWindow mw => mw,
                // GuiModalWindow is wrapped as GuiMainWindow by WrapComponent;
                // re-wrap the raw object as GuiMessageWindow so popup helpers work.
                GuiMainWindow mw => new GuiMessageWindow(mw.RawObject),
                _ => null,
            };
        }
        catch { return null; }
    }

    /// <summary>Returns a <see cref="GuiTree"/> by ID.</summary>
    public GuiTree Tree(string id) => FindById<GuiTree>(id);

    /// <summary>Returns a <see cref="GuiScrollContainer"/> by ID.</summary>
    public GuiScrollContainer ScrollContainer(string id) => FindById<GuiScrollContainer>(id);

    /// <summary>Returns the user area (content region) of a window by ID.
    /// Defaults to <c>wnd[0]/usr</c>.</summary>
    public GuiUserArea UserArea(string id = "wnd[0]/usr") => FindById<GuiUserArea>(id);

    /// <summary>Returns a <see cref="GuiCalendar"/> by ID.</summary>
    public GuiCalendar Calendar(string id) => FindById<GuiCalendar>(id);

    /// <summary>Returns a <see cref="GuiHTMLViewer"/> by ID.</summary>
    public GuiHTMLViewer HtmlViewer(string id) => FindById<GuiHTMLViewer>(id);

    /// <summary>Returns a <see cref="GuiShell"/> by ID.</summary>
    public GuiShell Shell(string id) => FindById<GuiShell>(id);

    /// <summary>
    /// Enters a transaction code, same as typing it in the command field and pressing Enter.
    /// <para>
    /// When called while already inside a transaction, prefix the code with <c>/n</c>
    /// to force SAP to navigate unconditionally, e.g. <c>"/nSE16"</c>.
    /// A bare code (e.g. <c>"SE16"</c>) is only reliable from the SAP Easy Access menu.
    /// Use <c>"/o"</c> prefix to open the transaction in a new parallel session.
    /// </para>
    /// </summary>
    public void StartTransaction(string tCode)
    {
        Logger.Info($"StartTransaction: {tCode}");
        try
        {
            FindById<GuiTextField>("wnd[0]/tbar[0]/okcd").Text = tCode;
            MainWindow().SendVKey(0); // VKey 0 = Enter
        }
        catch (Exception ex)
        {
            Logger.Error($"StartTransaction failed for '{tCode}': {ex.Message}", ex);
            throw;
        }
    }

    /// <summary>
    /// Exits the current transaction and returns to the SAP Easy Access menu.
    /// Equivalent to typing <c>/n</c> in the command field and pressing Enter.
    /// <para>
    /// Use <c>/nXX</c> via <see cref="StartTransaction"/> to jump directly to another
    /// transaction without returning to the menu first.
    /// </para>
    /// </summary>
    public void ExitTransaction()
    {
        Logger.Info("ExitTransaction");
        try
        {
            FindById<GuiTextField>("wnd[0]/tbar[0]/okcd").Text = "/n";
            MainWindow().SendVKey(0);
        }
        catch (Exception ex)
        {
            Logger.Error($"ExitTransaction failed: {ex.Message}", ex);
            throw;
        }
    }

    /// <summary>
    /// Sends a virtual key to the main window.
    /// <para>Common VKey codes:</para>
    /// <list type="table">
    ///   <listheader><term>VKey</term><description>Action</description></listheader>
    ///   <item><term>0</term> <description>Enter</description></item>
    ///   <item><term>3</term> <description>F3 — Back (one screen back within the transaction)</description></item>
    ///   <item><term>4</term> <description>F4 — Input Help / Possible Values</description></item>
    ///   <item><term>8</term> <description>F8 — Execute (runs the current report or selection screen)</description></item>
    ///   <item><term>11</term><description>Ctrl+S — Save</description></item>
    ///   <item><term>12</term><description>F12 — Cancel (discards changes and closes the current screen)</description></item>
    ///   <item><term>15</term><description>Shift+F3 — Exit (steps back to the previous menu level)</description></item>
    /// </list>
    /// </summary>
    public void SendVKey(int vKey) => MainWindow().SendVKey(vKey);

    /// <summary>Presses Enter on the main window (VKey 0).</summary>
    public void PressEnter() => SendVKey(0);

    /// <summary>Presses F3 / Back on the main window (VKey 3).</summary>
    public void PressBack() => SendVKey(3);

    /// <summary>
    /// Presses F8 / Execute on the main window (VKey 8).
    /// Equivalent to clicking the Execute button (<c>tbar[1]/btn[8]</c>) on a
    /// selection screen or transaction initial screen.
    /// </summary>
    public void PressExecute() => SendVKey(8);

    // ── Wait helper ───────────────────────────────────────────────────────────

    /// <summary>
    /// Waits until the session is no longer busy, polling every
    /// <paramref name="pollMs"/> milliseconds up to <paramref name="timeoutMs"/>.
    /// </summary>
    public void WaitReady(int timeoutMs = 30_000, int pollMs = 200)
    {
        var deadline = DateTime.UtcNow.AddMilliseconds(timeoutMs);
        bool warned = false;
        while (IsBusy && DateTime.UtcNow < deadline)
        {
            var remainingMs = (deadline - DateTime.UtcNow).TotalMilliseconds;
            if (!warned && remainingMs < Math.Max(500, timeoutMs * 0.15))
            {
                Logger.Warn($"WaitReady: session still busy with {remainingMs:F0} ms remaining (timeout={timeoutMs} ms).");
                warned = true;
            }
            System.Threading.Thread.Sleep(pollMs);
        }

        if (IsBusy)
        {
            var ex = new TimeoutException($"SAP session was still busy after {timeoutMs} ms.");
            Logger.Error(ex.Message, ex);
            throw ex;
        }
    }

    /// <summary>
    /// Like <see cref="WaitReady"/> but also verifies that the main window
    /// is reachable and that <see cref="IsBusy"/> stays <see langword="false"/>
    /// for one full <paramref name="settleMs"/> pause before returning.
    /// Use this instead of <see cref="WaitReady"/> when screen transitions
    /// trigger a brief second busy pulse that <see cref="WaitReady"/> misses.
    /// </summary>
    /// <param name="timeoutMs">Total time budget in ms. Default: 30 000.</param>
    /// <param name="pollMs">Polling interval in ms. Default: 200.</param>
    /// <param name="settleMs">Additional quiet period required before returning. Default: 200.</param>
    public void WaitForReadyState(int timeoutMs = 30_000, int pollMs = 200, int settleMs = 200)
    {
        var deadline = DateTime.UtcNow.AddMilliseconds(timeoutMs);
        bool warned = false;

        // Wait for busy flag to clear.
        while (IsBusy && DateTime.UtcNow < deadline)
        {
            var remainingMs = (deadline - DateTime.UtcNow).TotalMilliseconds;
            if (!warned && remainingMs < Math.Max(500, timeoutMs * 0.15))
            {
                Logger.Warn($"WaitForReadyState: session still busy with {remainingMs:F0} ms remaining (timeout={timeoutMs} ms).");
                warned = true;
            }
            System.Threading.Thread.Sleep(pollMs);
        }

        if (IsBusy)
        {
            var ex = new TimeoutException($"SAP session was still busy after {timeoutMs} ms.");
            Logger.Error(ex.Message, ex);
            throw ex;
        }

        // Settle: confirm main window is reachable and remains non-busy.
        System.Threading.Thread.Sleep(settleMs);

        if (IsBusy)
        {
            var ex = new TimeoutException("SAP session became busy again during the settle period.");
            Logger.Error(ex.Message, ex);
            throw ex;
        }

        // Verify the main window COM object is accessible.
        try { _ = MainWindow().Id; }
        catch (Exception ex)
        {
            var wrapped = new TimeoutException("SAP main window is not accessible after WaitForReadyState.", ex);
            Logger.Error(wrapped.Message, wrapped);
            throw wrapped;
        }
    }

    /// <summary>
    /// Polls until the component with <paramref name="id"/> exists and is accessible,
    /// or until <paramref name="timeoutMs"/> elapses.
    /// </summary>
    /// <param name="id">Component ID path, e.g. <c>"wnd[0]/usr/txtFoo"</c>.</param>
    /// <param name="timeoutMs">How long to poll in ms. Default: 10 000.</param>
    /// <param name="pollMs">Polling interval in ms. Default: 200.</param>
    /// <returns><see langword="true"/> if the component appeared within the timeout.</returns>
    public bool ElementExists(string id, int timeoutMs = 10_000, int pollMs = 200)
    {
        var deadline = DateTime.UtcNow.AddMilliseconds(timeoutMs);
        do
        {
            try
            {
                FindById(id);
                return true;
            }
            catch { }
            System.Threading.Thread.Sleep(pollMs);
        }
        while (DateTime.UtcNow < deadline);
        return false;
    }

    /// <summary>
    /// Polls until the component with <paramref name="id"/> is no longer accessible
    /// (throws on <see cref="FindById"/>), or until <paramref name="timeoutMs"/> elapses.
    /// Useful for waiting out loading spinners or processing dialogs.
    /// </summary>
    /// <param name="id">Component ID path to wait for disappearance.</param>
    /// <param name="timeoutMs">How long to poll in ms. Default: 10 000.</param>
    /// <param name="pollMs">Polling interval in ms. Default: 200.</param>
    /// <returns><see langword="true"/> if the component disappeared within the timeout.</returns>
    public bool WaitUntilHidden(string id, int timeoutMs = 10_000, int pollMs = 200)
    {
        var deadline = DateTime.UtcNow.AddMilliseconds(timeoutMs);
        do
        {
            try
            {
                FindById(id);
                // Still exists — keep polling.
            }
            catch
            {
                return true;
            }
            System.Threading.Thread.Sleep(pollMs);
        }
        while (DateTime.UtcNow < deadline);
        return false;
    }

    /// <summary>
    /// Returns a <see cref="RetryPolicy"/> that retries SAP operations on
    /// <see cref="SapComponentNotFoundException"/> (slow screen loads) and
    /// <see cref="TimeoutException"/> (session still busy).
    /// <para>Example:</para>
    /// <code>
    /// session.WithRetry(maxAttempts: 3, delayMs: 500).Run(() =>
    /// {
    ///     session.WaitReady();
    ///     session.TextField("wnd[0]/usr/txtFoo").Text = value;
    /// });
    /// </code>
    /// </summary>
    /// <param name="maxAttempts">Maximum number of attempts (≥ 1). Default: 3.</param>
    /// <param name="delayMs">Delay between attempts in ms. Default: 500.</param>
    public RetryPolicy WithRetry(int maxAttempts = 3, int delayMs = 500)
        => new RetryPolicy(maxAttempts, delayMs, Logger);

    // ── Post-login pop-up handling ────────────────────────────────────────────

    /// <summary>
    /// Automatically dismisses common post-SSO / post-login pop-up dialogs.
    ///
    /// <para>Call this immediately after obtaining a session from
    /// <see cref="SapGuiClient.LaunchWithSso(string, bool, int, SapLogAction?, SapLogLevel, ILogger?)"/> (or any other login flow) to
    /// clear system notices before starting automation.</para>
    ///
    /// <para>Dialogs handled (tried in this order):</para>
    /// <list type="bullet">
    ///   <item><description>
    ///     <b>Multiple Logon / User already logged on</b> –
    ///     clicks <em>Continue</em> to keep the existing session running and
    ///     start a new one in parallel.
    ///   </description></item>
    ///   <item><description>
    ///     <b>License expiration warnings</b> – clicks <em>OK</em>.
    ///   </description></item>
    ///   <item><description>
    ///     <b>System message banners / Message of the Day</b> – clicks <em>OK</em>.
    ///   </description></item>
    ///   <item><description>
    ///     <b>Any single-button information dialog</b> – presses that button.
    ///   </description></item>
    /// </list>
    ///
    /// <para>
    /// Unrecognised multi-button dialogs are left untouched so that automation
    /// does not blindly dismiss dialogs that require a deliberate choice.
    /// </para>
    ///
    /// <para>
    /// <b>Worst-case blocking time:</b> up to
    /// <c>maxPopups × timeoutMs + (maxPopups - 1) × 300 ms</c>.
    /// With the defaults (5 popups, 3 000 ms each) that is approximately
    /// 16.2 seconds when no popups appear at all.
    /// Reduce <paramref name="timeoutMs"/> if faster failure detection is needed.
    /// </para>
    /// </summary>
    /// <param name="maxPopups">
    ///   Maximum number of pop-ups to dismiss in a single call (default 5).
    ///   Guards against an unexpected dialog loop.
    /// </param>
    /// <param name="timeoutMs">
    ///   Time in milliseconds to wait for <b>each</b> pop-up to appear before
    ///   concluding there are no more (default 3 000 ms).
    /// </param>
    /// <returns>The number of pop-ups that were dismissed.</returns>
    public int DismissPostLoginPopups(int maxPopups = 5, int timeoutMs = 3_000)
    {
        int dismissed = 0;

        for (int attempt = 0; attempt < maxPopups; attempt++)
        {
            // Give SAP a moment to render the next popup after the previous dismissal.
            if (attempt > 0)
                System.Threading.Thread.Sleep(300);

            // Poll within the per-popup window.
            GuiMessageWindow? popup = null;
            var deadline = DateTime.UtcNow.AddMilliseconds(timeoutMs);
            while (popup is null && DateTime.UtcNow < deadline)
            {
                popup = GetActivePopup();
                if (popup is null)
                    System.Threading.Thread.Sleep(200);
            }

            if (popup is null) break; // no more popups

            Logger.Warn($"Post-login popup detected — Title: '{popup.Title}' | Text: '{popup.Text}' — attempting to dismiss.");
            bool handled = DismissPopup(popup);
            if (handled)
            {
                Logger.Info($"Post-login popup dismissed — Title: '{popup.Title}' | Text: '{popup.Text}'.");
                dismissed++;
            }
            else
            {
                Logger.Warn($"Post-login popup '{popup.Title}' was not recognised and was left open.");
                break; // unrecognised dialog – stop rather than risk data loss
            }
        }

        return dismissed;
    }

    /// <summary>
    /// Attempts to dismiss a single popup dialog using heuristics on the
    /// window title and message body text.
    /// Returns <see langword="true"/> when the popup was dismissed,
    /// <see langword="false"/> when it was not recognised.
    /// </summary>
    internal static bool DismissPopup(GuiMessageWindow popup)
    {
        string title = popup.Title.ToUpperInvariant();
        string text = popup.Text.ToUpperInvariant();

        // ── Multiple logon / user already logged on ───────────────────────────
        // SAP offers: "Terminate Other Logon" | "Continue" | "Cancel".
        // We choose "Continue" – keep both sessions alive.
        if (title.Contains("MULTIPLE LOGON") || title.Contains("ALREADY LOGGED ON") ||
            text.Contains("ALREADY LOGGED ON") || text.Contains("MULTIPLE LOGON"))
        {
            return TryClickButtonByText(popup, "Continue", "OK", "Yes")
                   || SafeClickOk(popup);
        }

        // ── License expiration ────────────────────────────────────────────────
        // Use "LICENSE EXPIR" (matches both "WILL EXPIRE" and "EXPIRED" in the title)
        // rather than the broad "LICENSE" to avoid auto-dismissing unrelated license
        // dialogs such as "Software License Agreement" confirmation prompts.
        if (title.Contains("LICENSE EXPIR") || text.Contains("LICENSE WILL EXPIRE") ||
            text.Contains("LICENSE EXPIRED"))
        {
            return TryClickButtonByText(popup, "OK", "Continue") || SafeClickOk(popup);
        }

        // ── System message / Message of the Day banners ───────────────────────
        if (title.Contains("SYSTEM MESSAGE") || title.Contains("MESSAGE OF THE DAY") ||
            text.Contains("SYSTEM MESSAGE"))
        {
            return TryClickButtonByText(popup, "OK", "Continue") || SafeClickOk(popup);
        }

        // ── Security / copyright notices (single-button) ──────────────────────
        var buttons = popup.GetButtons();
        if (buttons.Count == 1)
        {
            buttons[0].Press();
            return true;
        }

        // ── Generic OK-only fallback ──────────────────────────────────────────
        if (TryClickButtonByText(popup, "OK"))
            return true;

        // Multi-button dialog not matched by heuristics – leave it for the caller.
        return false;
    }

    /// <summary>
    /// Clicks the first button whose displayed text contains one of
    /// <paramref name="labels"/> (case-insensitive, tried left to right).
    /// Returns <see langword="true"/> on success.
    /// </summary>
    private static bool TryClickButtonByText(GuiMessageWindow popup, params string[] labels)
    {
        var buttons = popup.GetButtons();
        foreach (var label in labels)
        {
            foreach (var btn in buttons)
            {
                if (btn.Text.IndexOf(label, StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    btn.Press();
                    return true;
                }
            }
        }
        return false;
    }

    /// <summary>
    /// Sends VKey 0 (Enter / OK) to the popup, swallowing any COM exceptions.
    /// Returns <see langword="true"/> on success.
    /// </summary>
    private static bool SafeClickOk(GuiMessageWindow popup)
    {
        try { popup.ClickOk(); return true; }
        catch { return false; }
    }

    // ── Events ────────────────────────────────────────────────────────────────

    /// <summary>
    /// Fires after every SAP server round-trip completes (IsBusy transitions
    /// from <see langword="true"/> to <see langword="false"/>).
    /// Provides a snapshot of the status bar text and message type.
    /// <para>
    /// Call <see cref="StartMonitoring"/> to begin receiving events.
    /// </para>
    /// </summary>
    public event EventHandler<SessionChangeEventArgs>? Change;

    /// <summary>
    /// Fires when the session can no longer be accessed (i.e. the user closed
    /// the window or the connection was terminated).
    /// <para>
    /// Call <see cref="StartMonitoring"/> to begin receiving events.
    /// </para>
    /// </summary>
    public event EventHandler? Destroy;

    /// <summary>
    /// Fires when an ABAP abend is detected on the status bar
    /// (message type <c>A</c> after a round-trip).
    /// <para>
    /// Call <see cref="StartMonitoring"/> to begin receiving events.
    /// </para>
    /// </summary>
    public event EventHandler<AbapRuntimeErrorEventArgs>? AbapRuntimeError;

    /// <summary>
    /// Fires at the beginning of a SAP server round-trip
    /// (session transitions from idle to busy).
    /// <para>
    /// When the COM event sink is active this event arrives from a true COM
    /// source and gives precise timing.  In the polling fallback it fires when
    /// the background thread first observes <c>IsBusy = true</c>.
    /// </para>
    /// <para>Call <see cref="StartMonitoring"/> to begin receiving events.</para>
    /// </summary>
    public event EventHandler<StartRequestEventArgs>? StartRequest;

    /// <summary>
    /// Fires at the end of a SAP server round-trip
    /// (session transitions from busy to idle), before <see cref="Change"/>.
    /// <para>
    /// When the COM event sink is active <see cref="EndRequestEventArgs.FunctionCode"/>
    /// is populated.  In the polling fallback it is always empty.
    /// </para>
    /// <para>Call <see cref="StartMonitoring"/> to begin receiving events.</para>
    /// </summary>
    public event EventHandler<EndRequestEventArgs>? EndRequest;

    private SessionEventMonitor? _monitor;
    private GuiSessionComSink? _comSink;

    /// <summary>
    /// Starts event monitoring for this session.
    /// <para>
    /// <b>COM event sink (preferred):</b> On the first call, the wrapper tries to
    /// connect a COM event sink to the underlying SAP COM object via
    /// <c>IConnectionPointContainer</c>.  If successful, <see cref="Change"/>,
    /// <see cref="Destroy"/>, <see cref="AbapRuntimeError"/>,
    /// <see cref="StartRequest"/>, and <see cref="EndRequest"/> are all driven by
    /// the true SAP COM events — including a populated
    /// <see cref="SessionChangeEventArgs.FunctionCode"/>.
    /// </para>
    /// <para>
    /// <b>Polling fallback:</b> If the COM sink cannot connect (e.g. the SAP
    /// version does not expose <c>IConnectionPointContainer</c>), a background
    /// thread polls <c>IsBusy</c> every <paramref name="pollMs"/> milliseconds.
    /// <see cref="StartRequest"/> and <see cref="EndRequest"/> are approximated
    /// from <c>IsBusy</c> transitions; <c>FunctionCode</c> is always empty.
    /// </para>
    /// <para>Safe to call multiple times — subsequent calls are no-ops.</para>
    /// </summary>
    /// <param name="pollMs">Polling interval used only in the fallback path. Default 500 ms.</param>
    public void StartMonitoring(int pollMs = 500)
    {
        if (_monitor is not null || _comSink is not null) return;

        var sink = new GuiSessionComSink(this, RawObject);
        if (sink.IsConnected)
        {
            _comSink = sink;
        }
        else
        {
            sink.Dispose();
            _monitor = new SessionEventMonitor(this, pollMs);
        }
    }

    /// <summary>Stops the event monitor started by <see cref="StartMonitoring"/>.</summary>
    public void StopMonitoring()
    {
        _comSink?.Dispose();
        _comSink = null;
        _monitor?.Dispose();
        _monitor = null;
    }

    // ── IDisposable ───────────────────────────────────────────────────────────

    /// <summary>
    /// Stops event monitoring and releases the underlying COM RCW for this
    /// session immediately, rather than waiting for the GC finalizer.
    ///
    /// <para>
    /// <b>Does NOT log off or close the SAP window.</b>
    /// The session continues to run inside SAP GUI; only the .NET wrapper
    /// reference is released.  After <c>Dispose</c>, do not call any methods
    /// on this <see cref="GuiSession"/> instance.
    /// </para>
    ///
    /// <para>Safe to call multiple times.</para>
    /// </summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;

        string sessionId;
        try { sessionId = Id; } catch { sessionId = "(unknown)"; }
        Logger.Info($"GuiSession disposing: {sessionId}");

        // Disconnect COM event sinks / stop polling thread first so there
        // are no in-flight callbacks when we release the COM object.
        StopMonitoring();

        // Release the COM RCW so the reference is returned to COM immediately.
        // This prevents dangling COM objects from accumulating across long-running
        // automation processes and satisfies strict COM lifecycle policies.
        try
        {
            if (Marshal.IsComObject(RawObject))
                Marshal.ReleaseComObject(RawObject);
        }
        catch
        {
            // Best-effort: ignore COM errors during teardown.
        }
    }

    // ── Internal event raisers (called by SessionEventMonitor) ────────────────

    internal void RaiseChange(SessionChangeEventArgs args) =>
        Change?.Invoke(this, args);

    internal void RaiseDestroy() =>
        Destroy?.Invoke(this, EventArgs.Empty);

    internal void RaiseAbapRuntimeError(AbapRuntimeErrorEventArgs args) =>
        AbapRuntimeError?.Invoke(this, args);

    internal void RaiseStartRequest(StartRequestEventArgs args) =>
        StartRequest?.Invoke(this, args);

    internal void RaiseEndRequest(EndRequestEventArgs args) =>
        EndRequest?.Invoke(this, args);

    // ── Internal helpers ──────────────────────────────────────────────────────

    private object GetRawInfo()
    {
        return Invoke("Info")
               ?? throw new InvalidOperationException("Could not retrieve session Info object.");
    }

    /// <summary>
    /// Wraps a raw COM component object in the appropriate typed wrapper.
    /// </summary>
    internal static GuiComponent WrapComponent(object raw)
    {
        var typeName = string.Empty;
        try
        {
            typeName = (string?)raw.GetType()
                                   .InvokeMember("Type",
                                                 BindingFlags.GetProperty,
                                                 null, raw, null) ?? string.Empty;
        }
        catch { /* unknown type */ }

        return SapComponentTypeHelper.FromString(typeName) switch
        {
            SapComponentType.GuiMainWindow or
            SapComponentType.GuiFrameWindow or
            SapComponentType.GuiModalWindow => new GuiMainWindow(raw),

            SapComponentType.GuiTextField or
            SapComponentType.GuiCTextField or
            SapComponentType.GuiPasswordField or
            SapComponentType.GuiOkCodeField => new GuiTextField(raw),

            SapComponentType.GuiButton => new GuiButton(raw),
            SapComponentType.GuiCheckBox => new GuiCheckBox(raw),
            SapComponentType.GuiRadioButton => new GuiRadioButton(raw),
            SapComponentType.GuiComboBox => new GuiComboBox(raw),
            SapComponentType.GuiLabel => new GuiLabel(raw),
            SapComponentType.GuiStatusbar => new GuiStatusbar(raw),
            SapComponentType.GuiTable or
            SapComponentType.GuiTableControl => new GuiTable(raw),
            SapComponentType.GuiGridView => new GuiGridView(raw),
            SapComponentType.GuiTree => new GuiTree(raw),
            SapComponentType.GuiTabStrip => new GuiTabStrip(raw),
            SapComponentType.GuiTab => new GuiTab(raw),
            SapComponentType.GuiToolbar => new GuiToolbar(raw),
            SapComponentType.GuiMenubar => new GuiMenubar(raw),
            SapComponentType.GuiMenu or
            SapComponentType.GuiSubMenu => new GuiMenu(raw),
            SapComponentType.GuiContextMenu => new GuiContextMenu(raw),
            SapComponentType.GuiMessageWindow => new GuiMessageWindow(raw),
            SapComponentType.GuiScrollContainer => new GuiScrollContainer(raw),
            SapComponentType.GuiUserArea => new GuiUserArea(raw),
            SapComponentType.GuiCalendar => new GuiCalendar(raw),
            SapComponentType.GuiHTMLViewer => new GuiHTMLViewer(raw),
            SapComponentType.GuiShell => new GuiShell(raw),
            _ => new GuiComponent(raw),
        };
    }
}

// ── Session info record ───────────────────────────────────────────────────────

/// <summary>Read-only snapshot of <c>GuiSessionInfo</c> properties.</summary>
public class GuiSessionInfo
{
    private readonly object _raw;

    internal GuiSessionInfo(object raw) { _raw = raw; }

    private string Get(string prop)
    {
        try
        {
            return (string?)(_raw.GetType()
                                  .InvokeMember(prop,
                                                BindingFlags.GetProperty,
                                                null, _raw, null)) ?? string.Empty;
        }
        catch { return string.Empty; }
    }

    /// <summary>SAP system ID (SID), e.g. <c>GP1</c>.</summary>
    public string SystemName => Get("SystemName");

    /// <summary>Login client number, e.g. <c>450</c>.</summary>
    public string Client => Get("Client");

    /// <summary>Logged-on user name.</summary>
    public string User => Get("User");

    /// <summary>Login language, e.g. <c>EN</c>.</summary>
    public string Language => Get("Language");

    /// <summary>Active transaction code.</summary>
    public string Transaction => Get("Transaction");

    /// <summary>Active ABAP program name.</summary>
    public string Program => Get("Program");

    /// <summary>Current screen / dynpro number.</summary>
    public string ScreenNumber => Get("ScreenNumber");

    /// <summary>Application server hostname.</summary>
    public string ApplicationServer => Get("ApplicationServer");

    /// <inheritdoc/>
    public override string ToString() =>
        $"System={SystemName} Client={Client} User={User} TCode={Transaction}";
}
