namespace SapGui.Wrapper.Agent.Actions;

/// <summary>
/// Describes a single semantic operation to be executed by <see cref="SapAgentSession"/>.
/// Used as a lightweight record that can be logged, replayed, or unit-tested.
/// </summary>
public sealed class SapAction
{
    /// <summary>The kind of action to execute.</summary>
    public SapActionType ActionType { get; init; }

    /// <summary>
    /// Semantic target — field label, button text, transaction code, menu path,
    /// tab name, or tree node text, depending on <see cref="ActionType"/>.
    /// </summary>
    public string? Target { get; init; }

    /// <summary>
    /// For <see cref="SapActionType.SetField"/>: the value to write.
    /// For <see cref="SapActionType.HandlePopup"/> with <see cref="PopupAction.ByButtonText"/>:
    /// the button label to click.
    /// </summary>
    public string? Value { get; init; }

    /// <summary>
    /// Human-readable description of the action for audit logs and LLM history.
    /// Optional; auto-generated by <see cref="SapAgentSession"/> when omitted.
    /// </summary>
    public string? Description { get; init; }

    /// <inheritdoc/>
    public override string ToString() =>
        Description
        ?? $"{ActionType} target=\"{Target}\" value=\"{Value}\"";
}
